### ISSUE TITLE
LogSeq install should check if it's already been updated and not install if it has

### ISSUE THREAD

**Issue by corbob** [w0/au-packages#6]
LogSeq has an auto-update built in. If it is running when the Chocolatey Package is upgraded, it will close LogSeq, even though there is no need to actually upgrade the application.

LogSeq is not unique in this dilema, you can see it with vscode, gitkraken, and slack to name a few. I'm currently adding a handling of this to the gitkraken package, and would be more than willing to submit a PR to the logseq package for the same.

**Comment by w0** [comment]
Should be simple enough. I will work on adding this.

**Comment by w0** [comment]
fixed in bfa41e6
